import Navbar from "@/components/Navbar";
import "./globals.css";
import { Caveat, Inter } from "next/font/google"
import Footer from "@/components/Footer";
import Link from "next/link";
import { FaWhatsapp } from "react-icons/fa6";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",

});

const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
})

export const metadata = {
  title: "Chemistry Mint | Best coaching for NEET/JEE, 11th and 12th",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${caveat.variable}`}
    >
      <body className="min-h-full flex flex-col font-inter">
        <Link
          className="w-14 h-14 fixed bottom-6 right-6 z-50 bg-white rounded-full"
          href="https://wa.me/918468962451"
          target="_blank"
        ><FaWhatsapp className="inline w-full h-full text-green-500 text-4xl p-1.5"/></Link>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
